package clojure.storm;

import clojure.asm.Opcodes;
import clojure.lang.*;

public class OpcodesUtils {
    public static IPersistentSet accessKeys(int accessFlags) {
        IPersistentSet accSet = PersistentHashSet.EMPTY;

        if ((accessFlags & Opcodes.ACC_PUBLIC) != 0) accSet = (IPersistentSet) RT.conj(accSet,Keyword.intern(null,"public"));
        if ((accessFlags & Opcodes.ACC_PRIVATE) != 0) accSet = (IPersistentSet) RT.conj(accSet,Keyword.intern(null,"private"));
        if ((accessFlags & Opcodes.ACC_PROTECTED) != 0) accSet = (IPersistentSet) RT.conj(accSet,Keyword.intern(null,"protected"));
        if ((accessFlags & Opcodes.ACC_STATIC) != 0) accSet = (IPersistentSet) RT.conj(accSet,Keyword.intern(null,"static"));
        if ((accessFlags & Opcodes.ACC_FINAL) != 0) accSet = (IPersistentSet) RT.conj(accSet,Keyword.intern(null,"final"));

        return accSet;
    }
    public static Keyword opCodeKey(final int opcode) {
        switch (opcode) {
        case Opcodes.NOP: return Keyword.intern("nop");
        case Opcodes.ACONST_NULL: return Keyword.intern("aconst_null");
        case Opcodes.ICONST_M1: return Keyword.intern("iconst_m1");
        case Opcodes.ICONST_0: return Keyword.intern("iconst_0");
        case Opcodes.ICONST_1: return Keyword.intern("iconst_1");
        case Opcodes.ICONST_2: return Keyword.intern("iconst_2");
        case Opcodes.ICONST_3: return Keyword.intern("iconst_3");
        case Opcodes.ICONST_4: return Keyword.intern("iconst_4");
        case Opcodes.ICONST_5: return Keyword.intern("iconst_5");
        case Opcodes.LCONST_0: return Keyword.intern("lconst_0");
        case Opcodes.LCONST_1: return Keyword.intern("lconst_1");
        case Opcodes.FCONST_0: return Keyword.intern("fconst_0");
        case Opcodes.FCONST_1: return Keyword.intern("fconst_1");
        case Opcodes.FCONST_2: return Keyword.intern("fconst_2");
        case Opcodes.DCONST_0: return Keyword.intern("dconst_0");
        case Opcodes.DCONST_1: return Keyword.intern("dconst_1");
        case Opcodes.BIPUSH: return Keyword.intern("bipush");
        case Opcodes.SIPUSH: return Keyword.intern("sipush");
        case Opcodes.LDC: return Keyword.intern("ldc");
        case Opcodes.ILOAD: return Keyword.intern("iload");
        case Opcodes.LLOAD: return Keyword.intern("lload");
        case Opcodes.FLOAD: return Keyword.intern("fload");
        case Opcodes.DLOAD: return Keyword.intern("dload");
        case Opcodes.ALOAD: return Keyword.intern("aload");
        case Opcodes.IALOAD: return Keyword.intern("iaload");
        case Opcodes.LALOAD: return Keyword.intern("laload");
        case Opcodes.FALOAD: return Keyword.intern("faload");
        case Opcodes.DALOAD: return Keyword.intern("daload");
        case Opcodes.AALOAD: return Keyword.intern("aaload");
        case Opcodes.BALOAD: return Keyword.intern("baload");
        case Opcodes.CALOAD: return Keyword.intern("caload");
        case Opcodes.SALOAD: return Keyword.intern("saload");
        case Opcodes.ISTORE: return Keyword.intern("istore");
        case Opcodes.LSTORE: return Keyword.intern("lstore");
        case Opcodes.FSTORE: return Keyword.intern("fstore");
        case Opcodes.DSTORE: return Keyword.intern("dstore");
        case Opcodes.ASTORE: return Keyword.intern("astore");
        case Opcodes.IASTORE: return Keyword.intern("iastore");
        case Opcodes.LASTORE: return Keyword.intern("lastore");
        case Opcodes.FASTORE: return Keyword.intern("fastore");
        case Opcodes.DASTORE: return Keyword.intern("dastore");
        case Opcodes.AASTORE: return Keyword.intern("aastore");
        case Opcodes.BASTORE: return Keyword.intern("bastore");
        case Opcodes.CASTORE: return Keyword.intern("castore");
        case Opcodes.SASTORE: return Keyword.intern("sastore");
        case Opcodes.POP: return Keyword.intern("pop");
        case Opcodes.POP2: return Keyword.intern("pop2");
        case Opcodes.DUP: return Keyword.intern("dup");
        case Opcodes.DUP_X1: return Keyword.intern("dup_x1");
        case Opcodes.DUP_X2: return Keyword.intern("dup_x2");
        case Opcodes.DUP2: return Keyword.intern("dup2");
        case Opcodes.DUP2_X1: return Keyword.intern("dup2_x1");
        case Opcodes.DUP2_X2: return Keyword.intern("dup2_x2");
        case Opcodes.SWAP: return Keyword.intern("swap");
        case Opcodes.IADD: return Keyword.intern("iadd");
        case Opcodes.LADD: return Keyword.intern("ladd");
        case Opcodes.FADD: return Keyword.intern("fadd");
        case Opcodes.DADD: return Keyword.intern("dadd");
        case Opcodes.ISUB: return Keyword.intern("isub");
        case Opcodes.LSUB: return Keyword.intern("lsub");
        case Opcodes.FSUB: return Keyword.intern("fsub");
        case Opcodes.DSUB: return Keyword.intern("dsub");
        case Opcodes.IMUL: return Keyword.intern("imul");
        case Opcodes.LMUL: return Keyword.intern("lmul");
        case Opcodes.FMUL: return Keyword.intern("fmul");
        case Opcodes.DMUL: return Keyword.intern("dmul");
        case Opcodes.IDIV: return Keyword.intern("idiv");
        case Opcodes.LDIV: return Keyword.intern("ldiv");
        case Opcodes.FDIV: return Keyword.intern("fdiv");
        case Opcodes.DDIV: return Keyword.intern("ddiv");
        case Opcodes.IREM: return Keyword.intern("irem");
        case Opcodes.LREM: return Keyword.intern("lrem");
        case Opcodes.FREM: return Keyword.intern("frem");
        case Opcodes.DREM: return Keyword.intern("drem");
        case Opcodes.INEG: return Keyword.intern("ineg");
        case Opcodes.LNEG: return Keyword.intern("lneg");
        case Opcodes.FNEG: return Keyword.intern("fneg");
        case Opcodes.DNEG: return Keyword.intern("dneg");
        case Opcodes.ISHL: return Keyword.intern("ishl");
        case Opcodes.LSHL: return Keyword.intern("lshl");
        case Opcodes.ISHR: return Keyword.intern("ishr");
        case Opcodes.LSHR: return Keyword.intern("lshr");
        case Opcodes.IUSHR: return Keyword.intern("iushr");
        case Opcodes.LUSHR: return Keyword.intern("lushr");
        case Opcodes.IAND: return Keyword.intern("iand");
        case Opcodes.LAND: return Keyword.intern("land");
        case Opcodes.IOR: return Keyword.intern("ior");
        case Opcodes.LOR: return Keyword.intern("lor");
        case Opcodes.IXOR: return Keyword.intern("ixor");
        case Opcodes.LXOR: return Keyword.intern("lxor");
        case Opcodes.IINC: return Keyword.intern("iinc");
        case Opcodes.I2L: return Keyword.intern("i2l");
        case Opcodes.I2F: return Keyword.intern("i2f");
        case Opcodes.I2D: return Keyword.intern("i2d");
        case Opcodes.L2I: return Keyword.intern("l2i");
        case Opcodes.L2F: return Keyword.intern("l2f");
        case Opcodes.L2D: return Keyword.intern("l2d");
        case Opcodes.F2I: return Keyword.intern("f2i");
        case Opcodes.F2L: return Keyword.intern("f2l");
        case Opcodes.F2D: return Keyword.intern("f2d");
        case Opcodes.D2I: return Keyword.intern("d2i");
        case Opcodes.D2L: return Keyword.intern("d2l");
        case Opcodes.D2F: return Keyword.intern("d2f");
        case Opcodes.I2B: return Keyword.intern("i2b");
        case Opcodes.I2C: return Keyword.intern("i2c");
        case Opcodes.I2S: return Keyword.intern("i2s");
        case Opcodes.LCMP: return Keyword.intern("lcmp");
        case Opcodes.FCMPL: return Keyword.intern("fcmpl");
        case Opcodes.FCMPG: return Keyword.intern("fcmpg");
        case Opcodes.DCMPL: return Keyword.intern("dcmpl");
        case Opcodes.DCMPG: return Keyword.intern("dcmpg");
        case Opcodes.IFEQ: return Keyword.intern("ifeq");
        case Opcodes.IFNE: return Keyword.intern("ifne");
        case Opcodes.IFLT: return Keyword.intern("iflt");
        case Opcodes.IFGE: return Keyword.intern("ifge");
        case Opcodes.IFGT: return Keyword.intern("ifgt");
        case Opcodes.IFLE: return Keyword.intern("ifle");
        case Opcodes.IF_ICMPEQ: return Keyword.intern("if_icmpeq");
        case Opcodes.IF_ICMPNE: return Keyword.intern("if_icmpne");
        case Opcodes.IF_ICMPLT: return Keyword.intern("if_icmplt");
        case Opcodes.IF_ICMPGE: return Keyword.intern("if_icmpge");
        case Opcodes.IF_ICMPGT: return Keyword.intern("if_icmpgt");
        case Opcodes.IF_ICMPLE: return Keyword.intern("if_icmple");
        case Opcodes.IF_ACMPEQ: return Keyword.intern("if_acmpeq");
        case Opcodes.IF_ACMPNE: return Keyword.intern("if_acmpne");
        case Opcodes.GOTO: return Keyword.intern("goto");
        case Opcodes.JSR: return Keyword.intern("jsr");
        case Opcodes.RET: return Keyword.intern("ret");
        case Opcodes.TABLESWITCH: return Keyword.intern("tableswitch");
        case Opcodes.LOOKUPSWITCH: return Keyword.intern("lookupswitch");
        case Opcodes.IRETURN: return Keyword.intern("ireturn");
        case Opcodes.LRETURN: return Keyword.intern("lreturn");
        case Opcodes.FRETURN: return Keyword.intern("freturn");
        case Opcodes.DRETURN: return Keyword.intern("dreturn");
        case Opcodes.ARETURN: return Keyword.intern("areturn");
        case Opcodes.RETURN: return Keyword.intern("return");
        case Opcodes.GETSTATIC: return Keyword.intern("getstatic");
        case Opcodes.PUTSTATIC: return Keyword.intern("putstatic");
        case Opcodes.GETFIELD: return Keyword.intern("getfield");
        case Opcodes.PUTFIELD: return Keyword.intern("putfield");
        case Opcodes.INVOKEVIRTUAL: return Keyword.intern("invokevirtual");
        case Opcodes.INVOKESPECIAL: return Keyword.intern("invokespecial");
        case Opcodes.INVOKESTATIC: return Keyword.intern("invokestatic");
        case Opcodes.INVOKEINTERFACE: return Keyword.intern("invokeinterface");
        case Opcodes.INVOKEDYNAMIC: return Keyword.intern("invokedynamic");
        case Opcodes.NEW: return Keyword.intern("new");
        case Opcodes.NEWARRAY: return Keyword.intern("newarray");
        case Opcodes.ANEWARRAY: return Keyword.intern("anewarray");
        case Opcodes.ARRAYLENGTH: return Keyword.intern("arraylength");
        case Opcodes.ATHROW: return Keyword.intern("athrow");
        case Opcodes.CHECKCAST: return Keyword.intern("checkcast");
        case Opcodes.INSTANCEOF: return Keyword.intern("instanceof");
        case Opcodes.MONITORENTER: return Keyword.intern("monitorenter");
        case Opcodes.MONITOREXIT: return Keyword.intern("monitorexit");
        case Opcodes.MULTIANEWARRAY: return Keyword.intern("multianewarray");
        case Opcodes.IFNULL: return Keyword.intern("ifnull");
        case Opcodes.IFNONNULL: return Keyword.intern("ifnonnull");
        
        default:
            throw new IllegalArgumentException("Invalid opcode " + opcode);
            }
        }
    }
